### ISSUE TITLE
Netlify (Local?) Build Doesn't Properly Honor Custom Config File

### ISSUE THREAD

**Issue by patbakdev** [oliverroick/netlify-plugin-html-validate#15]
I believe that when a normal .htmlvalidate.json exists the plugin will ignore the config property. I have only validated this on my local machine using netlify-cli. I want to be able to run npx html-validate using the normal json config and a different one at build time.

**Files**
```
...
/.htmlvalidate.json
/.htmlvalidate.netlify.json
/netlify.toml
/public
...
```

**/netlify.toml**
```
[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.netlify.json"
```

**run `netlify build`**

**Result:**
```
  Plugin "netlify-plugin-html-validate" failed                  

  Error message
  Error: Invalid HTML
  Command failed with exit code 1: html-validate --config .htmlvalidate.netlify.json --ext html public
```

- It doesn't seem to matter what I name the file. It shows up as being used in the command line, but its clearly not since my rules are not firing properly.
- If I delete the the primary file `.htmlvalidate.json` then it works properly.

**Comment by oliverroick** [comment]
Hi @patbakdev, thank you for raising this. 

This behaviour is expected, although it's quite confusing. It's [documented here](https://html-validate.org/usage/cli.html#-c-config):

> Note that specifying a separate configuration file changes the default configuration but .htmlvalidate.json files will still be searched from the filesystem. 

Basically if a file named `.htmlvalidate.json` is present — either in the same directory or in any directory above — `html-validate` will still use the config in `.htmlvalidate.json`. 

If you put the [`"root": true`](https://html-validate.org/usage/index.html#root) flag into `.htmlvalidate.netlify.json`, `html-validate` will stop searching the file system for `.htmlvalidate.json` and use that config.

**Comment by patbakdev** [comment]
Ah. Not sure how I missed that. Its a little counter intuitive, but I thought I read over that page a number of times. Makes sense. Thanks.
