### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by ehmicky** [oliverroick/netlify-plugin-html-validate#3]
Would using the [programmatic API](https://html-validate.org/dev/using-api.html) instead of running the binary be better, e.g. in terms of speed or by providing more information? 

Using the binary might be simpler. Either way works, I was just wondering what your thoughts were? If it does not add any value, please feel free to close this issue.

**Comment by oliverroick** [comment]
Hey @ehmicky, thanks for raising this. 

I looked into the programmatic API a bit this afternoon; I think it's not worth making the changes at this point.

- We won't get much more information than what html-validate provides out of the box. 
- We would have some more flexibility in terms of formatting the errors/warnings, however that would require some work to build custom formatters. I think the output we're getting now is ok. 

Happy to revisit this in the future, if we see usage patterns emerge that would justify more customisation. For now, I prefer to keep it simple and stick with running the binary.

**Comment by ehmicky** [comment]
Makes sense! Thanks for looking into it :)
