### ISSUE TITLE
[SOLVED] Feature Request: Fails with default Hugo settings (minify) (UI install)

### ISSUE THREAD

**Issue by danielfdickinson** [oliverroick/netlify-plugin-html-validate#39]
When using the Hugo static generator with default build settings (which includes HTML minification), and this plugin with the default settings, the build fails.
This is because the 'validator' fails valid HTML5 that in its opinion is not a 'best practice' or which would fail on ancient browsers (that is the validator is an opinionated linter, not just validator)
This makes the plugin less widely useful than would otherwise be the case.

**Comment by oliverroick** [comment]
Hi @danielfdickinson, thanks for your interest in the plugin. 

`netlify-plugin-html-validate` isn't a validator itself, it's a wrapper around [html-validate](https://html-validate.org) to run html-validate on Netlify. html-validate is the piece that does the validation. 

html-validate has means to [configure custom validation rules](https://html-validate.org/usage/#configuration), I'm sure it's flexible enough to adapt to your use case. 

I might be able to help you set up the appropriate configuration If you provide an example for the HTML that fails to validate along with the errors your are seeing.

**Comment by danielfdickinson** [comment]
@oliverroick Thank you for responding. I was aware I could manual configuration but doing that is far down my priority queue (especially since once I start the full Netlify config (vs UI only) path, there are quite several things I'm going to have move from UI to config, and that's more work than I want to take on, now). This issue was more of a feature request for easy UI installation and use, in conjunction with Hugo. I do appreciate your offer, and I may eventually take you up on that.

**Comment by oliverroick** [comment]
You can configure custom validation rules without moving away from UI config. Add a `.htmlvalidate.json` and specify what you want to allow/disallow by following the [configuration instructions](https://html-validate.org/usage/#configuration). html-validate will pick up the custom config. 

---

As for the feature request, I'm not sure what feature you are asking for. The Netlify UI doesn't allow for much configuration, so we have no choice but to fall back on defaults. As I said in my previous comment, the validation is entirely done using html-validate, this plugin has no control over what html-validate does other than what you choose to configure. 

The presets html-validate uses will work for most websites. It's impossible to support _every_ use case there is. If you're not happy with the preset then you're going to have overwrite the default presets, especially if you want to validate HTML to support "ancient browsers."

**Comment by danielfdickinson** [comment]
Sorry for the confusion. ``.htmlvalidate.json`` is sufficient for my needs -- I missed that was an option, somehow.  As for 'ancient browsers', I meant for example requiring quotes by default is not required by HTML5 but is by ancient browsers, so that it seemed to me the validator's opinions were dated. That is unimportant though, since there is a way to configure as I wish, without having to get into non-UI Netlify configuration (yet; I could, it's just extra work, and I have enough already).

**Comment by danielfdickinson** [comment]
Thank you for your help. I discovered that I could replace the Hugo command from the UI, so I did ``hugo --gc`` instead of the default ``hugo --gc --minify``. Combined with the ``.htmlvalidator.json`` and ``.htmlvalidatorignore`` files, and a Netlify HTML minifier plugin the flow is much better, hence writing here in case others end up with a similar concern.
