### ISSUE TITLE
How to specify directories to validate

### ISSUE THREAD

**Issue by alesandroortiz** [oliverroick/netlify-plugin-html-validate#9]
Hello,

I was looking at the config for this plugin and `html-validate` itself, but don't seem to find how to specify directories to validate (or alternatively, directories to exclude). Is this possible with either the plugin or `html-validate`?

**Comment by oliverroick** [comment]
Hi @alesandroortiz,

specifying directories to validate is currently not possible, I'm afraid. The plugin validates the contents in the publish directory specified for the project. 

In `html-validate`, you can [set the directory, a specific file or a file-name pattern that you want to validate via the CLI](https://html-validate.org/usage/cli.html). (This plugin uses the CLI under the hood)

Adding an optional configuration parameter to customise, which directory to validate shouldn't be too difficult and it's something I can look into. Though, I would assume you would want to validate the output of your build before deploying so validating the publish directory makes sense. Could you tell me a bit about what you're trying to achieve and your context? Maybe there is a different solution which is better suited to your case.

**Comment by alesandroortiz** [comment]
Hi @oliverroick,

Thanks for the response. Most of the site content is Eleventy-generated production markup which I do want validated.

However, I have a couple of directories containing manually-created HTML files. These files are minimal test cases for browser or application bugs, therefore they tend to have non-production markup (e.g. missing `<head>` element, inline styles). In many cases, they have intentionally malformed markup.

For this particular site, it might be easier to use an Eleventy plugin combined with appropriate configuration. That way I could exclude those two directories from validation and validate everything else (top-level dir and other dirs). Also would validate at build time instead of at deploy time (even if it's a preview deploy).

**Comment by oliverroick** [comment]
I had a look at this and the changes required are minimal and it might be useful to other people as well. I have pushed the changes to [specify-directories](https://github.com/oliverroick/netlify-plugin-html-validate/tree/specify-directories). 

It's not yet released but you can test it using the [Netlify CLI](https://docs.netlify.com/cli/get-started). 

To get this setup you have to:

1. Clone this repository and checkout `specify-directories`
2. Change your `netlify.toml` to used the local version of the plugin:

```
// this is needed to run local plugins
[[plugins]]
    package = "@netlify/plugin-local-install-core"

[[plugins]]
  package = "{path_to_repo}/netlify-plugin-html-validate"
```

3. Add the path/files you want to validate:

```
[[plugins]]
  package = "{path_to_repo}/netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"
    path = "directory_to_validate"
```

If that works for you I can make a release with the changes

**Comment by alesandroortiz** [comment]
Appreciate the update! In my case, since I want to validate everything _except_ two directories, I don't think `html-validate` will work as-is. The `html-validate` package doesn't seem to support exclusions out of the box.

To make it clearer, this is analogous to my directory structure:

Want to validate:
```
/index.html
/404.html
/articles/index.html
/articles/article-1.html
/articles/article-2.html
/about/index.html
/other-dirs/other-content.html
```
Want to exclude:
```
/malformed/index.html
/malformed/abc/def.html
/badhtml/index.html
/badhtml/123/456.html
```

It seems I would need to call `html-validate` multiple times with `/index.html`, `/404.html`, `/articles/*`, `/about/*`, `/other-dirs/*`, etc. to ensure `/malformed/*`, and `/badhtml/*` are not processed. I'll also see if there's a similar validation package with existing support for all-but-exclusions, so I can specify something like `include: *.html, exclude: /malformed/*, /badhtml/*` and it would validate everything except those two directories.

**Comment by einSelbst** [comment]
Heyho,
the html-validate lib has the option to use [`.htmlvalidateignore`](https://html-validate.org/usage/#ignoring-files).
I'm using this mechanism to exclude `*.amp.html` files in my local `next.js` validation runs as those files have inlined css from there amp components.
Unfortunately it doesn't seem to be possible to pass this via cli, but I thought I mention it anyway as it fits the discussion and I would also like to be able to exclude patterns from the netlify validation runs.
My current workaround for my issue is disabling the inline-css check in a dedicated htmlvalidate config for netlify.

**Comment by oliverroick** [comment]
Hi @einSelbst, thank you for pointing this out. `.htmlvalidateignore` is a relatively new feature since 4.8; I had missed that it was introduced. 

netlify-plugin-html-validate currently installs `html-validate` 4.6.0, so support for `.htmlvalidateignore` is not available. In your `package.json`, you can specify which version of `html-validate` you want to install. You can specify any release > 4.8.0 and use `.htmlvalidateignore` today.

I'll update the dependencies and make a release at some point but I'm not sure when I'll get to it.

**Comment by alesandroortiz** [comment]
Thanks for the pointer @einSelbst!

Thanks for the manual instructions @oliverroick. I'll probably give it a try whenever the updated plugin is released or use the manual instructions if I have more time.

**Comment by oliverroick** [comment]
`html-validate` is updated to `^5.2.0`, which includes support for `.htmlvalidateignore`. Closing the ticket
